// frontend/src/components/home/AiAssistant.jsx
import React from 'react';

export default function AiAssistant({
  isOpen,
  setIsOpen,
  aiWinRef,
  aiBtnRef
}) {
  return (
    <>
      <div className="home-ai-fab z-50" title="Ask AI Assistant" ref={aiBtnRef} onClick={() => setIsOpen(!isOpen)}>
        <span className="material-symbols-outlined text-[28px]" style={{ fontVariationSettings: "'FILL' 1" }}>auto_awesome</span>
      </div>

      <div ref={aiWinRef} className={`home-ai-chat-window z-[60] ${isOpen ? 'open' : ''}`}>
        <div className="chat-header">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 bg-[#373549] rounded-lg flex items-center justify-center">
              <span className="material-symbols-outlined text-white text-[18px]">auto_awesome</span>
            </div>
            <span className="text-[16px] font-bold tracking-[-0.01em]">Lecto AI Assistant</span>
          </div>
          <button className="btn-ghost-icon p-1.5 rounded-lg text-[#8e8e93]" onClick={() => setIsOpen(false)}>
            <span className="material-symbols-outlined text-[20px]">close</span>
          </button>
        </div>
        <div className="chat-content custom-scrollbar">
          <div className="chat-bubble bubble-ai">
            안녕하세요! 어떤 것을 도와드릴까요? <br />강의 노트 요약이나 시험 문제 생성 등을 도와드릴 수 있습니다.
          </div>
          <div className="chat-bubble bubble-user">
            지난 '컴퓨터 네트워크' 수업 내용을 요약해줘.
          </div>
          <div className="chat-bubble bubble-ai">
            네, '컴퓨터 네트워크' 폴더의 최신 노트를 분석하여 요약해 드릴게요. <br /><br />
            1. OSI 7계층의 구조와 각 계층의 역할<br />
            2. TCP/IP 4계층 모델과의 차이점<br />
            3. 데이터 캡슐화와 비캡슐화 과정...
          </div>
        </div>
        <div className="chat-footer">
          <div className="chat-input-container">
            <input className="chat-input" placeholder="AI에게 질문해보세요..." type="text" />
            <button className="btn-ghost-icon p-1 text-[#373549]">
              <span className="material-symbols-outlined text-[20px]">send</span>
            </button>
          </div>
        </div>
      </div>
    </>
  );
}

// frontend/src/test_features/components/AiAssistant.vue
<script setup>
import { ref } from 'vue'

defineProps({
  isOpen: Boolean,
  aiWinRef: Object,
  aiBtnRef: Object
})

const emit = defineEmits(['update:isOpen'])

const inputText = ref('')
const isLoading = ref(false)
const messages = ref([
  { role: 'ai', text: '안녕하세요! 어떤 것을 도와드릴까요? 강의 노트 요약이나 시험 문제 생성 등을 도와드릴 수 있습니다.' }
])

async function sendMessage() {
  const question = inputText.value.trim()
  console.log('[AI Chat] sendMessage called, question:', question)
  if (!question) return

  messages.value.push({ role: 'user', text: question })
  inputText.value = ''
  isLoading.value = true

  try {
    const res = await fetch('/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ question }),
    })
    const data = await res.json()
    console.log('[AI Chat] response:', data)
    messages.value.push({ role: 'ai', text: data.answer })
  } catch (e) {
    console.error('[AI Chat] fetch error:', e)
    messages.value.push({ role: 'ai', text: '오류가 발생했습니다. 서버 연결을 확인해주세요.' })
  } finally {
    isLoading.value = false
  }
}
</script>

<template>
  <button
    class="absolute bottom-8 right-8 w-[64px] h-[64px] bg-gradient-to-r from-[#3b82f6] to-[#5856d6] rounded-full shadow-[0_8px_24px_rgba(59,130,246,0.3)] flex items-center justify-center text-white hover:scale-105 active:scale-95 transition-all z-40"
    id="home-ai-btn"
    @click="emit('update:isOpen', !isOpen)"
  >
    <span class="material-symbols-outlined text-[28px]">auto_awesome</span>
  </button>

  <div :class="['home-ai-chat-window z-[60]', { open: isOpen }]">
    <div class="chat-header">
      <div class="flex items-center gap-2.5">
        <div class="w-8 h-8 bg-[#373549] rounded-lg flex items-center justify-center">
          <span class="material-symbols-outlined text-white text-[18px]">auto_awesome</span>
        </div>
        <span class="text-[16px] font-bold tracking-[-0.01em]">Lecto AI Assistant</span>
      </div>
      <button class="btn-ghost-icon p-1.5 rounded-lg text-[#8e8e93]" @click="emit('update:isOpen', false)">
        <span class="material-symbols-outlined text-[20px]">close</span>
      </button>
    </div>

    <div class="chat-content custom-scrollbar">
      <div
        v-for="(msg, i) in messages"
        :key="i"
        :class="['chat-bubble', msg.role === 'ai' ? 'bubble-ai' : 'bubble-user']"
      >
        {{ msg.text }}
      </div>
      <div v-if="isLoading" class="chat-bubble bubble-ai">
        <span>...</span>
      </div>
    </div>

    <div class="chat-footer">
      <div class="chat-input-container">
        <input
          class="chat-input"
          placeholder="AI에게 질문해보세요..."
          type="text"
          v-model="inputText"
          @keyup.enter="sendMessage"
        />
        <button class="btn-ghost-icon p-1 text-[#373549]" @click="sendMessage">
          <span class="material-symbols-outlined text-[20px]">send</span>
        </button>
      </div>
    </div>
  </div>
</template>
