// frontend/src/pages/Workspace/Workspace.jsx
import LeftSidebar from '../../components/workspace/LeftSidebar';
import MainContent from '../../components/workspace/MainContent';
import RightSidebar from '../../components/workspace/RightSidebar';

export default function Workspace({
  onNavigateHome,
  transcriptions,
  onFileSelect,
  fileTree,
  setFileTree,
  favorites,
  setFavorites,
  isRecording,
  recordingTimeText,
  startRecording,
  stopRecording,
  activeFileName,
  onRightSidebarToggle,
  isRightSidebarVisible,
  summaryNotes,
  aiInput,
  setAiInput,
  onAddToNote,
  onAskAi
}) {
  return (
    <div className="p-[12px] flex gap-[12px] relative h-full w-full bg-[#ebebf0] text-[#1d1d1f] overflow-hidden">
      <LeftSidebar
        onNavigateHome={onNavigateHome}
        transcriptions={transcriptions}
        onFileSelect={onFileSelect}
        fileTree={fileTree}
        setFileTree={setFileTree}
        favorites={favorites}
        setFavorites={setFavorites}
        onAddToNote={onAddToNote}
        onAskAi={onAskAi}
      />
      <MainContent
        isRecording={isRecording}
        recordingTimeText={recordingTimeText}
        startRecording={startRecording}
        stopRecording={stopRecording}
        activeFileName={activeFileName}
        onRightSidebarToggle={onRightSidebarToggle}
        summaryNotes={summaryNotes}
      />
      <RightSidebar 
        visible={isRightSidebarVisible} 
        aiInput={aiInput}
        setAiInput={setAiInput}
      />
    </div>
  );
}

// frontend/src/pages/Workspace/Workspace.vue
<script setup>
import { ref } from 'vue'
import LeftSidebar from '../../components/workspace/LeftSidebar.vue'
import MainContent from '../../components/workspace/MainContent.vue'
import RightSidebar from '../../components/workspace/RightSidebar.vue'

defineProps({
  transcriptions: { type: Array, default: () => [] },
  fileTree: { type: Array, default: () => [] },
  favorites: { type: Set, default: () => new Set() },
  isRecording: { type: Boolean, default: false },
  recordingTimeText: { type: String, default: '0:00' },
  activeFileName: { type: String, default: '' },
  isRightSidebarVisible: { type: Boolean, default: true },
  summaryNotes: { type: Array, default: () => [] },
  aiInput: { type: String, default: '' }
})

const emit = defineEmits([
  'navigateHome',
  'fileSelect',
  'update:fileTree',
  'update:favorites',
  'update:aiInput',
  'startRecording',
  'stopRecording',
  'rightSidebarToggle',
  'addToNote',
  'askAi'
])

const isLeftSidebarCollapsed = ref(false)
</script>

<template>
  <div 
    class="p-[12px] flex relative h-full w-full bg-[#ebebf0] text-[#1d1d1f] overflow-hidden transition-all duration-400"
    :class="[
      { 'gap-[12px]': !isLeftSidebarCollapsed || isRightSidebarVisible }
    ]"
  >
    <LeftSidebar
      :isCollapsed="isLeftSidebarCollapsed"
      :transcriptions="transcriptions"
      :fileTree="fileTree"
      :favorites="favorites"
      @toggle="isLeftSidebarCollapsed = !isLeftSidebarCollapsed"
      @navigateHome="emit('navigateHome')"
      @fileSelect="(id, node) => emit('fileSelect', id, node)"
      @update:fileTree="emit('update:fileTree', $event)"
      @update:favorites="emit('update:favorites', $event)"
      @addToNote="(text, source) => emit('addToNote', text, source)"
      @askAi="(word) => emit('askAi', word)"
    />
    
    <MainContent
      :isRecording="isRecording"
      :recordingTimeText="recordingTimeText"
      :activeFileName="activeFileName"
      :summaryNotes="summaryNotes"
      @startRecording="emit('startRecording')"
      @stopRecording="emit('stopRecording')"
      @mainSidebarToggle="isLeftSidebarCollapsed = !isLeftSidebarCollapsed"
      @rightSidebarToggle="emit('rightSidebarToggle')"
    />
    
    <RightSidebar 
      :visible="isRightSidebarVisible" 
      :aiInput="aiInput"
      @update:aiInput="emit('update:aiInput', $event)"
    />
  </div>
</template>
