// frontend/src/pages/Home/Home.vue
<script setup>
import { computed } from 'vue'
import HomeSidebar from '../../components/home/HomeSidebar.vue'
import HomeBanner from '../../components/home/HomeBanner.vue'
import HomeGrid from '../../components/home/HomeGrid.vue'
import HomeModals from '../../components/home/HomeModals.vue'
import AiAssistant from '../../components/home/AiAssistant.vue'
import InfiniteGrid from '../../components/home/InfiniteGrid.vue'
import { useHome } from '../../composables/useHome'

const props = defineProps({
  fileTree: { type: Array, default: () => [] },
  favorites: { type: Set, default: () => new Set() }
})

const emit = defineEmits(['navigate', 'update:fileTree', 'update:favorites'])

const {
  isSidebarCollapsed,
  setIsSidebarCollapsed,
  isAiChatOpen,
  setIsAiChatOpen,
  isFolderModalOpen,
  isFileModalOpen,
  selectedColor,
  navigationStack,
  aiWinRef,
  aiBtnRef,
  newFolderName,
  newFileName,
  toggleStar,
  handleCreateFolder,
  handleCreateFile,
  handleEnterFolder,
  handleGoBack
} = useHome(props, emit)

const currentTitle = computed(() => {
  return navigationStack.value.length > 0
    ? navigationStack.value[navigationStack.value.length - 1].name
    : '내 폴더'
})

const currentItems = computed(() => {
  if (navigationStack.value.length === 0) return props.fileTree
  
  const currentFolderId = navigationStack.value[navigationStack.value.length - 1].id
  const findFolder = (nodes, id) => {
    for (const node of nodes) {
      if (node.id === id) return node
      if (node.children) {
        const found = findFolder(node.children, id)
        if (found) return found
      }
    }
    return null
  }
  const folder = findFolder(props.fileTree, currentFolderId)
  return folder ? (folder.children || []) : []
})
</script>

<template>
  <div class="p-[12px] flex gap-[12px] relative h-full w-full text-[#1d1d1f] overflow-hidden">
    <InfiniteGrid />
    <HomeSidebar 
      class="relative z-10"
      :isCollapsed="isSidebarCollapsed"
      :fileTree="fileTree"
      :favorites="favorites"
      @toggle="isSidebarCollapsed = !isSidebarCollapsed"
      @navigate="emit('navigate', $event)"
    />

    <main id="home-main-content" class="custom-scrollbar flex-1 overflow-y-auto relative z-10">
      <HomeBanner />
      
      <HomeGrid 
        :currentItems="currentItems"
        :currentTitle="currentTitle"
        :navigationStack="navigationStack"
        :favorites="favorites"
        @goBack="handleGoBack"
        @enterFolder="handleEnterFolder"
        @openFolderModal="isFolderModalOpen = true"
        @openFileModal="isFileModalOpen = true"
        @toggleStar="toggleStar"
        @navigate="emit('navigate', $event)"
      />
    </main>

    <AiAssistant 
      :isOpen="isAiChatOpen"
      :aiWinRef="aiWinRef"
      :aiBtnRef="aiBtnRef"
      @update:isOpen="isAiChatOpen = $event"
    />

    <HomeModals 
      :isFolderModalOpen="isFolderModalOpen"
      :isFileModalOpen="isFileModalOpen"
      :selectedColor="selectedColor"
      :newFolderName="newFolderName"
      :newFileName="newFileName"
      @update:isFolderModalOpen="isFolderModalOpen = $event"
      @update:isFileModalOpen="isFileModalOpen = $event"
      @update:selectedColor="selectedColor = $event"
      @update:newFolderName="newFolderName = $event"
      @update:newFileName="newFileName = $event"
      @createFolder="handleCreateFolder"
      @createFile="handleCreateFile"
    />
  </div>
</template>
<style src="./Home.css"></style>

// frontend/src/pages/Home/Home.jsx
import React from 'react';
import './Home.css';
import HomeSidebar from '../../components/home/HomeSidebar';
import HomeBanner from '../../components/home/HomeBanner';
import HomeGrid from '../../components/home/HomeGrid';
import AiAssistant from '../../components/home/AiAssistant';
import HomeModals from '../../components/home/HomeModals';
import useHome from './hooks/useHome';

export default function Home({ onNavigate, fileTree, setFileTree, favorites, setFavorites }) {
  const home = useHome({ fileTree, setFileTree, favorites, setFavorites });

  return (
    <div className="p-[12px] flex gap-[12px] relative h-full w-full bg-[#ebebf0] text-[#1d1d1f] overflow-hidden">
      <HomeSidebar
        isCollapsed={home.isSidebarCollapsed}
        setIsCollapsed={home.setIsSidebarCollapsed}
        onNavigate={onNavigate}
        fileTree={fileTree}
        favorites={favorites}
      />

      <main id="home-main-content" className="custom-scrollbar flex-1 overflow-y-auto">
        <HomeBanner />
        
        <HomeGrid
          items={home.currentItems}
          favorites={favorites}
          toggleStar={home.toggleStar}
          onEnterFolder={home.handleEnterFolder}
          onNavigate={onNavigate}
          navigationStack={home.navigationStack}
          onGoBack={home.handleGoBack}
          title={home.currentTitle}
          onOpenFolderModal={() => home.setIsFolderModalOpen(true)}
          onOpenFileModal={() => home.setIsFileModalOpen(true)}
        />
      </main>

      <AiAssistant
        isOpen={home.isAiChatOpen}
        setIsOpen={home.setIsAiChatOpen}
        aiWinRef={home.aiWinRef}
        aiBtnRef={home.aiBtnRef}
      />

      <HomeModals
        isFolderOpen={home.isFolderModalOpen}
        setIsFolderOpen={home.setIsFolderModalOpen}
        isFileOpen={home.isFileModalOpen}
        setIsFileOpen={home.setIsFileModalOpen}
        newFolderName={home.newFolderName}
        setNewFolderName={home.setNewFolderName}
        newFileName={home.newFileName}
        setNewFileName={home.setNewFileName}
        selectedColor={home.selectedColor}
        setSelectedColor={home.setSelectedColor}
        onCreateFolder={home.handleCreateFolder}
        onCreateFile={home.handleCreateFile}
      />
    </div>
  );
}
