// frontend/src/App.jsx
import React, { useState, useEffect, useRef, useCallback } from 'react';
import Workspace from './pages/Workspace/Workspace';
import Home from './pages/Home/Home';
import AiHistory from './pages/AiHistory/AiHistory';

export default function App() {
  // --- 상태 관리 (State) ---
  const [currentView, setCurrentView] = useState('home');
  const [isRecording, setIsRecording] = useState(false);
  const [recordingSeconds, setRecordingSeconds] = useState(0);
  const [transcriptions, setTranscriptions] = useState([]);
  const [activeFileName, setActiveFileName] = useState('강의1');
  const [isRightSidebarVisible, setIsRightSidebarVisible] = useState(true);

  // --- 추가된 통합 데이터 상태 ('정리 노트' 및 'AI 질문' 연동용) ---
  const [summaryNotes, setSummaryNotes] = useState([
    { id: 1, text: "데모 데이터: AI가 전사한 내용을 여기에 정리할 수 있습니다.", source: "AI 분석 결과", time: "12:00 PM" }
  ]);
  const [aiInput, setAiInput] = useState('');

  // --- 통합 데이터 상태 (Home & Sidebar 공유) ---
  const [fileTree, setFileTree] = useState(() => {
    const saved = localStorage.getItem('lecto_file_tree');
    return saved ? JSON.parse(saved) : [];
  });
  const [favorites, setFavorites] = useState(() => {
    const saved = localStorage.getItem('lecto_favorites');
    return saved ? new Set(JSON.parse(saved)) : new Set();
  });

  // 데이터 자동 저장
  useEffect(() => {
    localStorage.setItem('lecto_file_tree', JSON.stringify(fileTree));
  }, [fileTree]);

  useEffect(() => {
    localStorage.setItem('lecto_favorites', JSON.stringify(Array.from(favorites)));
  }, [favorites]);

  // --- 참조 관리 (Refs) ---
  const timerRef = useRef(null);
  const wsRef = useRef(null);
  const audioContextRef = useRef(null);
  const streamRef = useRef(null);
  const processorRef = useRef(null);
  const sourceRef = useRef(null);
  const lastBubbleTimeRef = useRef(0);
  const mockTimersRef = useRef([]);

  const float32ToInt16 = (float32Array) => {
    const int16Array = new Int16Array(float32Array.length);
    for (let i = 0; i < float32Array.length; i++) {
      const s = Math.max(-1, Math.min(1, float32Array[i]));
      int16Array[i] = s < 0 ? s * 32768 : s * 32767;
    }
    return int16Array;
  };

  const stopRecording = useCallback(() => {
    setIsRecording(false);
    clearInterval(timerRef.current);

    // 모의 타이머 정리
    mockTimersRef.current.forEach(t => clearTimeout(t));
    mockTimersRef.current = [];

    if (processorRef.current) { processorRef.current.disconnect(); processorRef.current = null; }
    if (sourceRef.current) { sourceRef.current.disconnect(); sourceRef.current = null; }
    if (audioContextRef.current) { audioContextRef.current.close(); audioContextRef.current = null; }
    if (streamRef.current) { streamRef.current.getTracks().forEach(track => track.stop()); streamRef.current = null; }
    if (wsRef.current) { wsRef.current.close(); wsRef.current = null; }
  }, []);

  const addTranscriptionBubble = useCallback((text) => {
    const now = new Date();
    const timeSpan = now.getTime() - lastBubbleTimeRef.current;

    setTranscriptions(prev => {
      const newItems = [...prev];
      if (newItems.length === 0 || timeSpan >= 3000) {
        newItems.push({
          time: now.toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit' }),
          text: text
        });
      } else {
        newItems[newItems.length - 1].text += " " + text;
      }
      return newItems;
    });

    lastBubbleTimeRef.current = now.getTime();
  }, []);

  const startRecording = useCallback(async () => {
    setIsRecording(true);
    setRecordingSeconds(0);

    timerRef.current = setInterval(() => {
      setRecordingSeconds(s => s + 1);
    }, 1000);

    // --- Mock Data 설정 --- 
    // 나중에 백엔드 서버를 사용할 때는 이 값을 false로 설정
    // 테스트용 텍스트는 true
    const USE_MOCK_DATA = true;

    if (USE_MOCK_DATA) {
      const t1 = setTimeout(() => {
        addTranscriptionBubble("안녕하세요, 실시간 음성 전사 테스트 중입니다.");
      }, 3000);
      const t2 = setTimeout(() => {
        addTranscriptionBubble("현재는 백엔드 연결 없이 샘플 데이터가 출력되고 있습니다.");
      }, 7000);
      mockTimersRef.current = [t1, t2];
      return;
    }

    // --- 실시간 백엔드 연결 (WebSocket) ---
    wsRef.current = new WebSocket("ws://100.104.164.84:8000/ws");

    wsRef.current.onmessage = (event) => {
      try {
        const data = JSON.parse(event.data);
        if (data.text && data.text.trim() !== "") {
          addTranscriptionBubble(data.text);
        }
      } catch (e) {
        console.log("Error parsing JSON:", e);
      }
    };

    wsRef.current.onopen = async () => {
      try {
        const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
        streamRef.current = stream;

        const audioContext = new AudioContext();
        audioContextRef.current = audioContext;

        await audioContext.audioWorklet.addModule("/pcm-worklet.js");

        const source = audioContext.createMediaStreamSource(stream);
        sourceRef.current = source;

        const processor = new AudioWorkletNode(audioContext, "pcm-worklet");
        processorRef.current = processor;

        source.connect(processor);
        processor.connect(audioContext.destination);

        processor.port.onmessage = (event) => {
          const data = float32ToInt16(event.data);
          if (wsRef.current && wsRef.current.readyState === WebSocket.OPEN) {
            wsRef.current.send(data.buffer);
          }
        };
      } catch (error) {
        console.error("Error accessing microphone:", error);
        stopRecording();
      }
    };
  }, [addTranscriptionBubble, stopRecording]);

  useEffect(() => {
    return () => { stopRecording(); };
  }, [stopRecording]);

  const minutes = Math.floor(recordingSeconds / 60);
  const seconds = recordingSeconds % 60;
  const recordingTimeText = `${minutes}:${seconds.toString().padStart(2, '0')}`;

  // 파일 선택 핸들러 (LeftSidebar -> MainContent 연결)
  const handleFileSelect = useCallback((id, node) => {
    if (node) setActiveFileName(node.name);
  }, []);

  // 우측 사이드바 토글
  const handleRightSidebarToggle = useCallback(() => {
    setIsRightSidebarVisible(prev => !prev);
  }, []);

  // --- 추가된 핸들러 ('정리 노트' 및 'AI 질문' 연동용) ---
  const handleAddToNote = useCallback((text, source) => {
    const now = new Date();
    setSummaryNotes(prev => [
      ...prev,
      {
        id: Date.now(),
        text: text,
        source: source || 'AI 분석 결과',
        time: now.toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit' })
      }
    ]);
  }, []);

  const handleAskAi = useCallback((word) => {
    setAiInput(word);
    setIsRightSidebarVisible(true);
  }, []);

  if (currentView === 'ai-history') {
    return (
      <AiHistory onNavigateBack={() => setCurrentView('home')} />
    );
  }

  if (currentView === 'home') {
    return (
      <Home
        onNavigate={(view) => setCurrentView(view)}
        fileTree={fileTree}
        setFileTree={setFileTree}
        favorites={favorites}
        setFavorites={setFavorites}
      />
    );
  }

  return (
    <Workspace
      onNavigateHome={() => setCurrentView('home')}
      transcriptions={transcriptions}
      onFileSelect={handleFileSelect}
      fileTree={fileTree}
      setFileTree={setFileTree}
      favorites={favorites}
      setFavorites={setFavorites}
      isRecording={isRecording}
      recordingTimeText={recordingTimeText}
      startRecording={startRecording}
      stopRecording={stopRecording}
      activeFileName={activeFileName}
      onRightSidebarToggle={handleRightSidebarToggle}
      isRightSidebarVisible={isRightSidebarVisible}
      summaryNotes={summaryNotes}
      aiInput={aiInput}
      setAiInput={setAiInput}
      onAddToNote={handleAddToNote}
      onAskAi={handleAskAi}
    />
  );
}

// frontend/src/App.vue
<script setup>
import { ref, onMounted, onUnmounted, watch } from 'vue'
import Workspace from './pages/Workspace/Workspace.vue'
import Home from './pages/Home/Home.vue'
import Workfolder from './pages/Workfolder/Workfolder.vue'
import AiHistory from './pages/AiHistory/AiHistory.vue'

// --- 상태 관리 (State) ---
const currentView = ref('home')
const isRecording = ref(false)
const recordingSeconds = ref(0)
const transcriptions = ref([])
const activeFileName = ref('강의1')
const isRightSidebarVisible = ref(true)

// --- 추가된 통합 데이터 상태 ---
const summaryNotes = ref([
  { id: 1, text: "데모 데이터: AI가 전사한 내용을 여기에 정리할 수 있습니다.", source: "AI 분석 결과", time: "12:00 PM" }
])
const aiInput = ref('')

// --- 통합 데이터 상태 (Home & Sidebar 공유) ---
const fileTree = ref([])
const favorites = ref(new Set())

onMounted(() => {
  const savedTree = localStorage.getItem('lecto_file_tree')
  if (savedTree) fileTree.value = JSON.parse(savedTree)
  
  const savedFavs = localStorage.getItem('lecto_favorites')
  if (savedFavs) favorites.value = new Set(JSON.parse(savedFavs))
})

watch(fileTree, (newVal) => {
  localStorage.setItem('lecto_file_tree', JSON.stringify(newVal))
}, { deep: true })

watch(favorites, (newVal) => {
  localStorage.setItem('lecto_favorites', JSON.stringify(Array.from(newVal)))
}, { deep: true })

// --- 참조 관리 (Refs) ---
let timer = null
let ws = null
let audioContext = null
let stream = null
let processor = null
let audioSource = null
let lastBubbleTime = 0
let mockTimers = []

const float32ToInt16 = (float32Array) => {
  const int16Array = new Int16Array(float32Array.length)
  for (let i = 0; i < float32Array.length; i++) {
    const s = Math.max(-1, Math.min(1, float32Array[i]))
    int16Array[i] = s < 0 ? s * 32768 : s * 32767
  }
  return int16Array
}

const stopRecording = () => {
  isRecording.value = false
  clearInterval(timer)

  mockTimers.forEach(t => clearTimeout(t))
  mockTimers = []

  if (processor) { processor.disconnect(); processor = null }
  if (audioSource) { audioSource.disconnect(); audioSource = null }
  if (audioContext) { audioContext.close(); audioContext = null }
  if (stream) { stream.getTracks().forEach(track => track.stop()); stream = null }
  if (ws) { ws.close(); ws = null }
}

let segIdCounter = 0

const addTranscriptionBubble = (text, status = 'confirmed') => {
  const now = new Date()
  const timeSpan = now.getTime() - lastBubbleTime
  const segId = ++segIdCounter

  if (transcriptions.value.length === 0 || timeSpan >= 3000) {
    transcriptions.value.push({
      time: now.toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit' }),
      text: text,
      segments: [{ id: segId, text, status }]
    })
  } else {
    const lastIdx = transcriptions.value.length - 1
    const t = transcriptions.value[lastIdx]
    t.segments.push({ id: segId, text, status })
    t.text = t.segments.map(s => s.text).join(' ')
  }

  lastBubbleTime = now.getTime()
  return segId
}

const updateLastSegment = (rawText, correctedText) => {
  if (transcriptions.value.length === 0) return
  const t = transcriptions.value[transcriptions.value.length - 1]
  // 가장 최근의 pending 세그먼트를 역순으로 찾음 (rawText 우선, 없으면 가장 최근 pending)
  let segIdx = [...t.segments].map((s, i) => i).reverse().find(
    i => t.segments[i].status === 'pending' && t.segments[i].rawText === rawText
  )
  // fallback: rawText 매칭 없을 경우 가장 최근 pending 사용
  if (segIdx === undefined) {
    segIdx = [...t.segments].map((s, i) => i).reverse().find(
      i => t.segments[i].status === 'pending'
    )
  }
  if (segIdx !== undefined) {
    // Vue 반응성을 위해 splice로 객체 교체
    t.segments.splice(segIdx, 1, {
      ...t.segments[segIdx],
      text: correctedText,
      status: 'confirmed'
    })
    t.text = t.segments.map(s => s.text).join(' ')
  }
}

const startRecording = async () => {
  isRecording.value = true
  recordingSeconds.value = 0

  timer = setInterval(() => {
    recordingSeconds.value++
  }, 1000)

  // Mock Data 설정
  // 전사 테스트
  const USE_MOCK_DATA = false

  if (USE_MOCK_DATA) {
    const t1 = setTimeout(() => {
      addTranscriptionBubble("안녕하세요, 실시간 음성 전사 테스트 중입니다.")
    }, 3000)
    const t2 = setTimeout(() => {
      addTranscriptionBubble("현재는 백엔드 연결 없이 샘플 데이터가 출력되고 있습니다.")
    }, 7000)
    mockTimers = [t1, t2]
    return
  }

  // --- 실시간 백엔드 연결 (WebSocket) ---
  // 웹 서켓과 백엔드하고 연동- aki
  // 
  ws = new WebSocket("ws://100.104.164.84:8000/ws")

  ws.onmessage = (event) => {
    try {
      const data = JSON.parse(event.data)
      if (data.text && data.text.trim() !== "") {
        if (data.type === 'corrected') {
          // pending 상태가 최소 400ms 동안 보이도록 딜레이 후 교정 적용
          const rawText = data.raw_text
          const correctedText = data.text
          setTimeout(() => {
            updateLastSegment(rawText, correctedText)
          }, 400)
        } else {
          // raw 텍스트 추가: rawText 저장 + 자동 confirmed 타임아웃 설정
          const segId = ++segIdCounter
          const now = new Date()
          const timeSpan = now.getTime() - lastBubbleTime
          const rawText = data.text

          if (transcriptions.value.length === 0 || timeSpan >= 3000) {
            transcriptions.value.push({
              time: now.toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit' }),
              text: rawText,
              segments: [{ id: segId, text: rawText, rawText, status: 'pending' }]
            })
          } else {
            const lastIdx = transcriptions.value.length - 1
            const t = transcriptions.value[lastIdx]
            t.segments.push({ id: segId, text: rawText, rawText, status: 'pending' })
            t.text = t.segments.map(s => s.text).join(' ')
          }
          lastBubbleTime = now.getTime()

          // 백엔드가 corrected를 보내지 않는 경우(교정 불필요 or 교정 disabled)를 위한 자동 confirmed 처리
          // 2.5초 후에도 pending 상태이면 confirmed로 자동 전환
          setTimeout(() => {
            for (const trans of transcriptions.value) {
              const segIdx = trans.segments.findIndex(s => s.id === segId && s.status === 'pending')
              if (segIdx !== -1) {
                trans.segments.splice(segIdx, 1, {
                  ...trans.segments[segIdx],
                  status: 'confirmed'
                })
                trans.text = trans.segments.map(s => s.text).join(' ')
                break
              }
            }
          }, 2500)
        }
      }
    } catch (e) {
      console.log("Error parsing JSON:", e)
    }
  }

  ws.onopen = async () => {
    try {
      stream = await navigator.mediaDevices.getUserMedia({ audio: true })
      audioContext = new AudioContext()
      await audioContext.audioWorklet.addModule("/pcm-worklet.js")

      audioSource = audioContext.createMediaStreamSource(stream)
      processor = new AudioWorkletNode(audioContext, "pcm-worklet")

      audioSource.connect(processor)
      processor.connect(audioContext.destination)

      processor.port.onmessage = (event) => {
        const data = float32ToInt16(event.data)
        if (ws && ws.readyState === WebSocket.OPEN) {
          ws.send(data.buffer)
        }
      }
    } catch (error) {
      console.error("Error accessing microphone:", error)
      stopRecording()
    }
  }
}

onUnmounted(() => {
  stopRecording()
})

const formatTime = () => {
  const minutes = Math.floor(recordingSeconds.value / 60)
  const seconds = recordingSeconds.value % 60
  return `${minutes}:${seconds.toString().padStart(2, '0')}`
}

const handleFileSelect = (id, node) => {
  if (node) activeFileName.value = node.name
}

const handleRightSidebarToggle = () => {
  isRightSidebarVisible.value = !isRightSidebarVisible.value
}

const handleAddToNote = (text, source) => {
  const now = new Date()
  summaryNotes.value.push({
    id: Date.now(),
    text: text,
    source: source || 'AI 분석 결과',
    time: now.toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit' })
  })
}

const handleAskAi = (word) => {
  aiInput.value = word
  isRightSidebarVisible.value = true
}

const handleNavigate = (view) => {
  currentView.value = view
}
</script>

<template>
  <AiHistory 
    v-if="currentView === 'ai-history'" 
    @navigateBack="handleNavigate('home')" 
  />

  <Workfolder 
    v-else-if="currentView === 'workfolder'"
    :fileTree="fileTree"
    :favorites="favorites"
    @update:fileTree="fileTree = $event"
    @update:favorites="favorites = $event"
    @navigate="handleNavigate"
  />

  <Home 
    v-else-if="currentView === 'home'"
    :fileTree="fileTree"
    :favorites="favorites"
    @update:fileTree="fileTree = $event"
    @update:favorites="favorites = $event"
    @navigate="handleNavigate"
  />

  <Workspace 
    v-else
    :fileTree="fileTree"
    :favorites="favorites"
    :transcriptions="transcriptions"
    :isRecording="isRecording"
    :recordingTimeText="formatTime()"
    :activeFileName="activeFileName"
    :isRightSidebarVisible="isRightSidebarVisible"
    :summaryNotes="summaryNotes"
    :aiInput="aiInput"
    @update:fileTree="fileTree = $event"
    @update:favorites="favorites = $event"
    @update:aiInput="aiInput = $event"
    @navigateHome="handleNavigate('home')"
    @fileSelect="handleFileSelect"
    @startRecording="startRecording"
    @stopRecording="stopRecording"
    @rightSidebarToggle="handleRightSidebarToggle"
    @addToNote="handleAddToNote"
    @askAi="handleAskAi"
  />
</template>
